/* Hindi text for the main calculator (index.html). Loaded only when Hindi is chosen (see i18n.js).
   I18N_DICT: exact English text → Hindi.  I18N_RULES: patterns for text that contains numbers or names.
   To change a translation, edit the Hindi on the right. Keep the English on the left exactly as it appears on the page. */
(function () {
const MON = { Jan: "जन", Feb: "फ़र", Mar: "मार्च", Apr: "अप्रैल", May: "मई", Jun: "जून", Jul: "जुल", Aug: "अग", Sep: "सित", Oct: "अक्टू", Nov: "नव", Dec: "दिस" };
const MONTH = { January: "जनवरी", February: "फ़रवरी", March: "मार्च", April: "अप्रैल", May: "मई", June: "जून", July: "जुलाई", August: "अगस्त", September: "सितंबर", October: "अक्टूबर", November: "नवंबर", December: "दिसंबर" };
const mon = s => s.replace(/\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b/g, m => MON[m]);
const rg = r => r.toLowerCase() === "new" ? "नई कर व्यवस्था" : "पुरानी कर व्यवस्था";

window.I18N_DICT = {
  // Header, navigation, tabs
  "Pay Commission Calculator": "वेतन आयोग कैलकुलेटर",
  "Guides": "गाइड", "News": "समाचार", "FAQ": "FAQ", "About": "हमारे बारे में", "Contact": "संपर्क", "Sources": "स्रोत",
  "Terms of Use": "उपयोग की शर्तें", "Privacy Policy": "गोपनीयता नीति",
  "7th Pay Commission": "7वां वेतन आयोग", "8th Pay Commission": "8वां वेतन आयोग",
  "Monthly pay": "मासिक वेतन", "Arrears": "एरियर",
  "Your details": "आपका विवरण", "Reset": "रीसेट",
  "Calculator reset to the starting values.": "कैलकुलेटर शुरुआती मानों पर रीसेट हो गया।",
  // Pay
  "Pay": "वेतन",
  "Pay Matrix level": "पे मैट्रिक्स लेवल",
  "Shown with the old 6th CPC Grade Pay. University and college teachers: pick your Academic Grade Pay (AGP).": "पुराने 6वें वेतन आयोग के ग्रेड पे के साथ दिखाया गया है। विश्वविद्यालय और कॉलेज शिक्षक: अपना एकेडमिक ग्रेड पे (AGP) चुनें।",
  "Basic pay (7th CPC Pay Matrix)": "मूल वेतन (7वें वेतन आयोग का पे मैट्रिक्स)",
  "Basic pay (current 7th CPC → estimated 8th CPC)": "मूल वेतन (वर्तमान 7वां → अनुमानित 8वां वेतन आयोग)",
  "Other amount…": "अन्य राशि…",
  "Your 7th CPC basic pay ₹": "आपका 7वें वेतन आयोग का मूल वेतन ₹",
  "7th CPC Pay Matrix (6th CPC Grade Pay)": "7वें वेतन आयोग का पे मैट्रिक्स (6वें का ग्रेड पे)",
  "Academic Pay Matrix · UGC (Academic Grade Pay)": "एकेडमिक पे मैट्रिक्स · UGC (एकेडमिक ग्रेड पे)",
  // 8th CPC
  "8th Pay Commission estimates": "8वें वेतन आयोग के अनुमान",
  "Fitment factor": "फिटमेंट फैक्टर",
  "Not yet announced. Choose an estimate or type your own.": "अभी घोषित नहीं हुआ। कोई अनुमान चुनें या अपना लिखें।",
  // Arrears inputs
  "Arrears period": "एरियर अवधि",
  "8th CPC effective from": "8वां वेतन आयोग प्रभावी तिथि",
  "The date the new pay counts from. Expected to be 1 January 2026.": "जिस तिथि से नया वेतन गिना जाएगा। 1 जनवरी 2026 होने की उम्मीद है।",
  "New pay actually starts from": "नया वेतन वास्तव में कब से मिलेगा",
  "The first month the 8th CPC salary is paid. Arrears cover every month before it.": "वह पहला महीना जब 8वें वेतन आयोग का वेतन मिलेगा। उससे पहले के सभी महीनों का एरियर बनता है।",
  "Choose another month…": "दूसरा महीना चुनें…",
  "Month the new pay starts": "नया वेतन शुरू होने का महीना",
  "Expected DA rise every 6 months": "हर 6 महीने में DA में अपेक्षित वृद्धि",
  "Used for both 7th and 8th CPC DA during the arrears period. 7th CPC DA is 60% from January 2026.": "एरियर अवधि में 7वें और 8वें दोनों वेतन आयोगों के DA के लिए। 7वें वेतन आयोग का DA जनवरी 2026 से 60% है।",
  "Include yearly increment every July (3%)": "हर जुलाई की वार्षिक वेतनवृद्धि (3%) शामिल करें",
  "Include in arrears": "एरियर में शामिल करें",
  "(basic pay and DA are always included)": "(मूल वेतन और DA हमेशा शामिल हैं)",
  "House Rent Allowance (HRA)": "मकान किराया भत्ता (HRA)",
  "Transport Allowance": "परिवहन भत्ता",
  "Your city for transport allowance": "परिवहन भत्ते के लिए आपका शहर",
  "Big cities (Class X) get a higher transport allowance.": "बड़े शहरों (श्रेणी X) में परिवहन भत्ता अधिक मिलता है।",
  "Higher-rate city · Class X (Delhi, Mumbai, Kolkata…)": "उच्च दर वाला शहर · श्रेणी X (दिल्ली, मुंबई, कोलकाता…)",
  "Other city · Class Y or Z": "अन्य शहर · श्रेणी Y या Z",
  "Deduct NPS / UPS from arrears": "एरियर से NPS / UPS काटें",
  "In the 7th CPC, arrears were paid on basic pay and DA only; HRA and other allowances were revised later without arrears. NPS uses the percentage set under Deductions. Use your basic pay as it was on the effective date.": "7वें वेतन आयोग में एरियर केवल मूल वेतन और DA पर मिला था; HRA और अन्य भत्ते बाद में बिना एरियर के संशोधित हुए। NPS के लिए कटौतियों में दिया गया प्रतिशत लगता है। प्रभावी तिथि पर जो मूल वेतन था, वही डालें।",
  "Work out income tax on arrears": "एरियर पर आयकर की गणना करें",
  "Tax regime for arrears": "एरियर के लिए कर व्यवस्था",
  "New regime (default)": "नई कर व्यवस्था (डिफ़ॉल्ट)", "Old regime": "पुरानी कर व्यवस्था", "New regime": "नई कर व्यवस्था",
  "Claim relief under Section 89 (Form 10E)": "धारा 89 के तहत राहत लें (फ़ॉर्म 10E)",
  // HRA
  "House Rent Allowance": "मकान किराया भत्ता",
  "Search your city": "अपना शहर खोजें",
  "e.g. Pune, Lucknow, Kochi": "जैसे पुणे, लखनऊ, कोच्चि",
  "Pick a city to set the HRA class, or choose the class yourself below.": "HRA श्रेणी तय करने के लिए शहर चुनें, या नीचे स्वयं श्रेणी चुनें।",
  "Keep typing and pick your city from the list.": "टाइप करते रहें और सूची से अपना शहर चुनें।",
  "HRA class": "HRA श्रेणी",
  "X · 50 lakh+ cities (Delhi, Mumbai…)": "X · 50 लाख+ आबादी वाले शहर (दिल्ली, मुंबई…)",
  "Y · other large cities": "Y · अन्य बड़े शहर",
  "Z · rest of India": "Z · शेष भारत",
  "HRA rates under 8th CPC": "8वें वेतन आयोग में HRA दरें",
  "Not announced yet. Today's rates are 30/20/10% because DA is above 50%.": "अभी घोषित नहीं। आज की दरें 30/20/10% हैं क्योंकि DA 50% से ऊपर है।",
  "Same as today · 30 / 20 / 10%": "आज जैसी · 30 / 20 / 10%",
  "24 / 16 / 8% · reset, as when the 7th CPC started": "24 / 16 / 8% · रीसेट, जैसा 7वें वेतन आयोग की शुरुआत में हुआ",
  "Follow 8th CPC DA (7th CPC rule)": "8वें वेतन आयोग के DA के अनुसार (7वें का नियम)",
  // DA
  "Dearness Allowance": "महंगाई भत्ता",
  "DA under 7th CPC": "7वें वेतन आयोग में DA", "DA under 8th CPC": "8वें वेतन आयोग में DA",
  "Used to compare with your current pay.": "आपके वर्तमान वेतन से तुलना के लिए।",
  "Resets to 0% when a new pay commission starts, then rises every six months.": "नया वेतन आयोग शुरू होने पर 0% हो जाता है, फिर हर छह महीने बढ़ता है।",
  "Enter DA % manually…": "DA % स्वयं लिखें…", "Enter DA % (7th CPC)": "DA % लिखें (7वां वेतन आयोग)", "Enter DA % (8th CPC)": "DA % लिखें (8वां वेतन आयोग)",
  "60% · from Jan 2026 (current)": "60% · जनवरी 2026 से (वर्तमान)",
  "63% · Jul 2026 (expected)": "63% · जुलाई 2026 (अपेक्षित)", "66% · Jan 2027 (expected)": "66% · जनवरी 2027 (अपेक्षित)", "69% · Jul 2027 (expected)": "69% · जुलाई 2027 (अपेक्षित)",
  "58% · Jul 2025": "58% · जुलाई 2025", "55% · Jan 2025": "55% · जनवरी 2025", "53% · Jul 2024": "53% · जुलाई 2024", "50% · Jan 2024": "50% · जनवरी 2024",
  "0% · when 8th CPC starts": "0% · 8वां वेतन आयोग शुरू होने पर", "3% · after 6 months (expected)": "3% · 6 महीने बाद (अपेक्षित)", "6% · after 1 year (expected)": "6% · 1 वर्ष बाद (अपेक्षित)",
  "9% · after 18 months (expected)": "9% · 18 महीने बाद (अपेक्षित)", "12% · after 2 years (expected)": "12% · 2 वर्ष बाद (अपेक्षित)",
  // Allowances and deductions
  "Other allowances": "अन्य भत्ते", "None added": "कुछ नहीं जोड़ा", "Deductions": "कटौतियाँ", "None": "कोई नहीं",
  "Add an allowance": "भत्ता जोड़ें", "Add a deduction": "कटौती जोड़ें", "Name": "नाम", "Amount per month": "मासिक राशि", "Remove": "हटाएँ", "₹ / month": "₹ / माह", "₹ / year": "₹ / वर्ष",
  "Children Education Allowance": "बाल शिक्षा भत्ता", "+ Children Education Allowance": "+ बाल शिक्षा भत्ता",
  "Special Duty Allowance": "विशेष ड्यूटी भत्ता", "+ Special Duty Allowance": "+ विशेष ड्यूटी भत्ता",
  "Overtime Allowance": "ओवरटाइम भत्ता", "+ Overtime Allowance": "+ ओवरटाइम भत्ता",
  "Night Duty Allowance": "रात्रि ड्यूटी भत्ता", "+ Night Duty Allowance": "+ रात्रि ड्यूटी भत्ता",
  "+ Custom": "+ अपना जोड़ें", "+ CGHS": "+ CGHS", "+ CGEGIS": "+ CGEGIS",
  "GPF subscription": "GPF अंशदान", "+ GPF subscription": "+ GPF अंशदान",
  "Professional tax": "व्यवसाय कर", "+ Professional tax": "+ व्यवसाय कर",
  "Loan / advance recovery": "ऋण / अग्रिम वसूली", "+ Loan / advance recovery": "+ ऋण / अग्रिम वसूली",
  "Other": "अन्य",
  "Pension contribution": "पेंशन अंशदान", "Pension scheme": "पेंशन योजना", "Pension contribution percent": "पेंशन अंशदान प्रतिशत",
  "Percent of basic pay + DA. Untick if you are on GPF (old pension scheme) or add GPF below.": "मूल वेतन + DA का प्रतिशत। यदि आप GPF (पुरानी पेंशन योजना) पर हैं तो टिक हटाएँ या नीचे GPF जोड़ें।",
  "Scheme and percent of the extra basic pay + DA deducted from arrears.": "योजना और अतिरिक्त मूल वेतन + DA का प्रतिशत जो एरियर से कटेगा।",
  // Income tax inputs
  "Income tax": "आयकर", "Deduct income tax from take-home": "इन-हैंड वेतन से आयकर घटाएँ", "Tax regime": "कर व्यवस्था",
  "Old regime deductions": "पुरानी कर व्यवस्था की कटौतियाँ", "(yearly amounts, used for the old regime and the comparison)": "(वार्षिक राशि, पुरानी व्यवस्था और तुलना के लिए)",
  "Rent paid": "दिया गया किराया", "80C investments": "80C निवेश", "80CCD(1B) extra NPS": "80CCD(1B) अतिरिक्त NPS", "80D health insurance": "80D स्वास्थ्य बीमा", "Home loan interest": "गृह ऋण ब्याज",
  "up to ₹50,000": "₹50,000 तक", "up to ₹2,00,000": "₹2,00,000 तक",
  "80C already includes your NPS/UPS contribution and any GPF you added. Add PPF, LIC, ELSS, tuition fees and similar here.": "80C में आपका NPS/UPS अंशदान और जोड़ा गया GPF पहले से शामिल है। PPF, LIC, ELSS, ट्यूशन फ़ीस आदि यहाँ जोड़ें।",
  "Not deducted": "नहीं घटाया",
  // Results
  "Monthly take-home · 7th CPC": "मासिक इन-हैंड वेतन · 7वां वेतन आयोग",
  "Estimated monthly take-home · 8th CPC": "अनुमानित मासिक इन-हैंड वेतन · 8वां वेतन आयोग",
  "Gross": "सकल", "Tax": "कर", "vs 7th CPC": "7वें वेतन आयोग की तुलना में",
  "Monthly pay statement": "मासिक वेतन विवरण", "Component": "घटक", "7th CPC": "7वां वेतन आयोग", "8th CPC (est.)": "8वां (अनुमान)",
  "Basic pay": "मूल वेतन", "Transport Allowance + DA": "परिवहन भत्ता + DA", "Gross salary": "सकल वेतन",
  "Total deductions": "कुल कटौतियाँ", "Take-home pay": "इन-हैंड वेतन",
  "See detailed tax breakdown": "कर का विस्तृत ब्योरा देखें",
  "New regime is better": "नई कर व्यवस्था बेहतर है", "Old regime is better": "पुरानी कर व्यवस्था बेहतर है",
  "The": "", "new regime": "नई कर व्यवस्था", "old regime": "पुरानी कर व्यवस्था",
  "you chose is better here, saving": "(आपकी चुनी हुई) यहाँ बेहतर है, बचत",
  "you chose is better here.": "(आपकी चुनी हुई) यहाँ बेहतर है।",
  "a year.": "प्रति वर्ष।",
  "would save you": "से आपकी बचत होगी",
  "a year. Change it under Income tax.": "प्रति वर्ष। इसे आयकर सेक्शन में बदलें।",
  "New regime": "नई कर व्यवस्था",
  "Gross salary (12 months)": "सकल वेतन (12 महीने)", "HRA exemption": "HRA छूट", "Standard deduction": "मानक कटौती",
  "80C (incl. NPS/UPS, GPF)": "80C (NPS/UPS, GPF सहित)", "Taxable income": "कर योग्य आय", "Tax as per slabs": "स्लैब के अनुसार कर",
  "Rebate u/s 87A": "धारा 87A के तहत छूट", "Surcharge": "अधिभार", "Health & education cess (4%)": "स्वास्थ्य एवं शिक्षा उपकर (4%)",
  "Total tax for the year": "वर्ष का कुल कर", "Tax per month": "प्रति माह कर",
  "Income slab": "आय स्लैब", "Rate": "दर", "Your income in slab": "स्लैब में आपकी आय",
  "7th CPC pay": "7वें वेतन आयोग का वेतन", "8th CPC pay (estimate)": "8वें वेतन आयोग का वेतन (अनुमान)",
  "Assumes 12 months at this monthly pay. Uses the slab rates set in the Union Budget 2025. Employer NPS contribution is left out because it is added to income and deducted again under 80CCD(2).": "इस मासिक वेतन पर 12 महीने मानकर। केंद्रीय बजट 2025 की स्लैब दरें। नियोक्ता का NPS अंशदान शामिल नहीं है, क्योंकि वह आय में जुड़कर 80CCD(2) के तहत फिर घट जाता है।",
  "Download pay slip (PDF)": "पे स्लिप डाउनलोड करें (PDF)",
  "Share this result (opens with your figures filled in):": "यह परिणाम शेयर करें (आपके आंकड़ों के साथ खुलेगा):",
  "Copy link": "लिंक कॉपी करें",
  // Arrears results
  "Estimated arrears receivable": "अनुमानित प्राप्य एरियर",
  "Estimated arrears receivable after tax": "कर के बाद अनुमानित प्राप्य एरियर",
  "Gross arrears": "सकल एरियर",
  "Show month-by-month arrears": "माह-वार एरियर देखें",
  "Period": "अवधि", "7th CPC paid": "7वें वेतन आयोग में मिला", "8th CPC due": "8वें वेतन आयोग में देय", "per month": "प्रति माह",
  "Total arrears": "कुल एरियर", "Income tax on arrears": "एरियर पर आयकर", "Arrears in hand": "हाथ में एरियर",
  "See how tax on arrears is worked out": "एरियर पर कर की गणना देखें",
  "Taxable income for the year without arrears (at 8th CPC pay)": "एरियर के बिना वर्ष की कर योग्य आय (8वें वेतन आयोग के वेतन पर)",
  "Add: arrears received": "जोड़ें: प्राप्त एरियर", "Tax without arrears": "एरियर के बिना कर", "Tax with arrears": "एरियर सहित कर",
  "Extra tax because of arrears": "एरियर के कारण अतिरिक्त कर",
  "Section 89 relief · arrears spread back to the years they belong to": "धारा 89 राहत · एरियर उन वर्षों में बाँटा गया जिनसे वह संबंधित है",
  "Year": "वर्ष", "Arrears for that year": "उस वर्ष का एरियर", "Extra tax in that year": "उस वर्ष में अतिरिक्त कर", "Total": "कुल",
  "Extra tax if taxed in their own years": "अपने-अपने वर्षों में कर लगने पर अतिरिक्त कर",
  "Relief under Section 89": "धारा 89 के तहत राहत", "Relief under Section 89 (not claimed)": "धारा 89 के तहत राहत (दावा नहीं किया)",
  "Estimated tax on arrears:": "एरियर पर अनुमानित कर:",
  "after": "(धारा 89 राहत",
  "Section 89 relief. Arrears in hand:": "के बाद)। हाथ में एरियर:",
  ". Arrears in hand:": "। हाथ में एरियर:",
  ".": "।",
  "Earlier years use your 7th CPC taxable income from the Monthly pay view as the base; the year of receipt uses your 8th CPC taxable income. Slab rates from the Union Budget 2025 are applied to every year. To claim relief, file Form 10E on the income tax portal before filing your return.": "पिछले वर्षों के लिए 'मासिक वेतन' वाली 7वें वेतन आयोग की कर योग्य आय आधार है; प्राप्ति वाले वर्ष के लिए 8वें वेतन आयोग की कर योग्य आय। हर वर्ष पर केंद्रीय बजट 2025 की स्लैब दरें लगाई गई हैं। राहत के लिए रिटर्न भरने से पहले आयकर पोर्टल पर फ़ॉर्म 10E भरें।",
  "Choose a start month after the effective date.": "प्रभावी तिथि के बाद का शुरुआती महीना चुनें।",
  "Yearly increments are added every July.": "हर जुलाई वार्षिक वेतनवृद्धि जोड़ी गई है।",
  "Arrears are taxable in the year you receive them; you can reduce the extra tax by claiming relief under Section 89 (Form 10E).": "एरियर पर उसी वर्ष कर लगता है जिसमें वह मिलता है; धारा 89 (फ़ॉर्म 10E) के तहत राहत लेकर अतिरिक्त कर घटाया जा सकता है।",
  "All figures are estimates until the 8th CPC is notified.": "8वें वेतन आयोग की अधिसूचना तक सभी आंकड़े अनुमान हैं।",
  // Phone bar
  "Monthly take-home": "मासिक इन-हैंड वेतन", "Take-home / month": "इन-हैंड / माह", "8th CPC take-home / month": "8वें वेतन आयोग में इन-हैंड / माह",
  "Arrears receivable": "प्राप्य एरियर", "See details": "विवरण देखें",
  // More calculators
  "More calculators": "अन्य कैलकुलेटर", "Pension": "पेंशन", "Basic pension, DR, commutation, family pension": "मूल पेंशन, DR, कम्यूटेशन, पारिवारिक पेंशन",
  "NPS vs UPS": "NPS बनाम UPS", "Compare your pension under both schemes": "दोनों योजनाओं में अपनी पेंशन की तुलना करें",
  "Gratuity": "ग्रेच्युटी", "Gratuity and leave encashment at retirement": "सेवानिवृत्ति पर ग्रेच्युटी और अवकाश नकदीकरण",
  "Pay Matrix": "पे मैट्रिक्स", "Basic pay for every level and cell": "हर लेवल और सेल का मूल वेतन",
  // How this is worked out
  "How this is worked out": "यह कैसे गणना होती है",
  "Pay and DA": "वेतन और DA",
  "Basic pay comes from the 7th CPC Pay Matrix, or the UGC Academic Pay Matrix for teachers. Each step in a level is 3% higher, rounded to the nearest ₹100.": "मूल वेतन 7वें वेतन आयोग के पे मैट्रिक्स से, और शिक्षकों के लिए UGC एकेडमिक पे मैट्रिक्स से लिया गया है। लेवल का हर अगला चरण 3% अधिक होता है, निकटतम ₹100 तक पूर्णांकित।",
  "Dearness Allowance is a percentage of basic pay. It is 60% from January 2026, or the rate you choose.": "महंगाई भत्ता मूल वेतन का प्रतिशत है। जनवरी 2026 से यह 60% है, या आपकी चुनी दर।",
  "HRA is a percentage of basic pay by city class: 30/20/10% when DA is 50% or more, 27/18/9% between 25% and 50%, and 24/16/8% below 25%.": "HRA शहर की श्रेणी के अनुसार मूल वेतन का प्रतिशत है: DA 50% या अधिक होने पर 30/20/10%, 25% से 50% के बीच 27/18/9%, और 25% से कम पर 24/16/8%।",
  "Minimum HRA is ₹5,400 (X), ₹3,600 (Y) and ₹1,800 (Z) a month.": "न्यूनतम HRA ₹5,400 (X), ₹3,600 (Y) और ₹1,800 (Z) प्रति माह है।",
  "The city search uses the X and Y city lists. Noida, Ghaziabad, Gurugram and Faridabad are treated as Delhi. Any city not listed is Class Z.": "शहर खोज X और Y शहरों की सूची पर आधारित है। नोएडा, गाज़ियाबाद, गुरुग्राम और फ़रीदाबाद को दिल्ली माना गया है। सूची में न होने वाला हर शहर श्रेणी Z है।",
  "Uses the 7th CPC slabs by level, with X class cities treated as higher-rate cities, plus DA on the allowance.": "लेवल के अनुसार 7वें वेतन आयोग के स्लैब, X श्रेणी के शहरों को उच्च दर वाले शहर मानकर, और भत्ते पर DA सहित।",
  "New basic pay = 7th CPC basic pay × the fitment factor you choose, rounded to ₹100.": "नया मूल वेतन = 7वें वेतन आयोग का मूल वेतन × आपका चुना फिटमेंट फैक्टर, ₹100 तक पूर्णांकित।",
  "DA restarts at 0% unless you choose otherwise. HRA uses the 8th CPC rates you pick (today’s 30/20/10% by default). Transport allowance follows the 7th CPC rules.": "DA 0% से शुरू होता है, जब तक आप कुछ और न चुनें। HRA आपकी चुनी 8वें वेतन आयोग की दरों पर (डिफ़ॉल्ट रूप से आज की 30/20/10%)। परिवहन भत्ता 7वें वेतन आयोग के नियमों पर।",
  "For each month from the effective date until the new pay starts: 8th CPC pay due minus 7th CPC pay actually paid, on basic pay and DA (plus HRA and transport allowance if you tick them).": "प्रभावी तिथि से नया वेतन शुरू होने तक हर महीने: 8वें वेतन आयोग का देय वेतन घटा 7वें वेतन आयोग का वास्तव में मिला वेतन, मूल वेतन और DA पर (टिक करने पर HRA और परिवहन भत्ता भी)।",
  "DA on both sides rises by the amount you choose every January and July, and the yearly increment is added every July.": "दोनों ओर का DA हर जनवरी और जुलाई में आपकी चुनी दर से बढ़ता है, और हर जुलाई वार्षिक वेतनवृद्धि जुड़ती है।",
  "Tax on arrears is worked out for the year you receive them, with Section 89 relief if selected.": "एरियर पर कर उसी वर्ष के लिए गिना जाता है जिसमें वह मिलता है, चुनने पर धारा 89 राहत सहित।",
  "Allowances and deductions": "भत्ते और कटौतियाँ",
  "Allowances and deductions you add use the same monthly amount in both pay commissions.": "आपके जोड़े गए भत्ते और कटौतियाँ दोनों वेतन आयोगों में समान मासिक राशि पर गिनी जाती हैं।",
  "Suggested amounts (CGHS and CGEGIS by level, Children Education Allowance for one child, professional tax) can be edited.": "सुझाई गई राशियाँ (लेवल के अनुसार CGHS और CGEGIS, एक बच्चे का बाल शिक्षा भत्ता, व्यवसाय कर) बदली जा सकती हैं।",
  "NPS/UPS is the percentage you set of basic pay plus DA.": "NPS/UPS मूल वेतन + DA का आपका चुना प्रतिशत है।",
  "Worked out for a full year at the monthly pay shown, using the new and old regime slab rates from the Union Budget 2025, with the standard deduction, 87A rebate, surcharge and 4% cess.": "दिखाए गए मासिक वेतन पर पूरे वर्ष के लिए, केंद्रीय बजट 2025 की नई और पुरानी व्यवस्था की स्लैब दरों से, मानक कटौती, 87A छूट, अधिभार और 4% उपकर सहित।",
  "More detail in the": "अधिक जानकारी", "guides": "गाइड में", ":": ":", "fitment factor": "फिटमेंट फैक्टर", ",": ",", "DA history": "DA इतिहास",
  "HRA city classes": "HRA शहर श्रेणियाँ", "and": "और", "arrears and Section 89": "एरियर व धारा 89",
  ". All official sources are listed on the": "। सभी आधिकारिक स्रोतों की सूची", "page.": "पेज पर है।",
  // Disclaimer and footer
  "Disclaimer": "अस्वीकरण",
  "Results are estimates for guidance only. This is not an official Government tool, and nothing here is tax, legal or financial advice.": "परिणाम केवल मार्गदर्शन के लिए अनुमान हैं। यह आधिकारिक सरकारी टूल नहीं है, और यहाँ कुछ भी कर, कानूनी या वित्तीय सलाह नहीं है।",
  "For information only.": "केवल जानकारी के लिए।",
  "This calculator gives estimates for general guidance. It is not an official tool and does not replace your pay slip, pay fixation order, or any order issued by your department.": "यह कैलकुलेटर सामान्य मार्गदर्शन के लिए अनुमान देता है। यह आधिकारिक टूल नहीं है और आपकी पे स्लिप, वेतन निर्धारण आदेश या आपके विभाग के किसी आदेश की जगह नहीं लेता।",
  "Not affiliated with the Government.": "सरकार से संबद्ध नहीं।",
  "This website is independent. It is not connected to, endorsed by, or run on behalf of the Government of India, any State Government, the Ministry of Finance, DoPT, UGC, or any Pay Commission.": "यह वेबसाइट स्वतंत्र है। यह भारत सरकार, किसी राज्य सरकार, वित्त मंत्रालय, DoPT, UGC या किसी वेतन आयोग से जुड़ी, उनके द्वारा समर्थित या उनकी ओर से संचालित नहीं है।",
  "8th Pay Commission figures are projections.": "8वें वेतन आयोग के आंकड़े अनुमान हैं।",
  "The 8th CPC fitment factor, pay matrix, DA and allowance rates have not been notified. All 8th CPC amounts are assumptions and may differ from what is finally announced.": "8वें वेतन आयोग का फिटमेंट फैक्टर, पे मैट्रिक्स, DA और भत्तों की दरें अधिसूचित नहीं हुई हैं। 8वें वेतन आयोग की सभी राशियाँ अनुमान हैं और अंतिम घोषणा से अलग हो सकती हैं।",
  "Not tax, legal or financial advice.": "कर, कानूनी या वित्तीय सलाह नहीं।",
  "Income tax figures are approximate and leave out many personal factors. Consult a qualified tax professional or your Drawing and Disbursing Officer (DDO) before making decisions.": "आयकर के आंकड़े अनुमानित हैं और कई व्यक्तिगत बातें शामिल नहीं करते। निर्णय से पहले किसी योग्य कर विशेषज्ञ या अपने आहरण एवं संवितरण अधिकारी (DDO) से सलाह लें।",
  "Check before you rely on it.": "भरोसा करने से पहले जाँच लें।",
  "Pay matrix values, DA and HRA rates, city classes and tax slabs are compiled from public sources and may contain errors or be out of date. Always confirm with official Government notifications.": "पे मैट्रिक्स, DA और HRA दरें, शहर श्रेणियाँ और कर स्लैब सार्वजनिक स्रोतों से लिए गए हैं और इनमें त्रुटि हो सकती है या ये पुराने हो सकते हैं। हमेशा आधिकारिक सरकारी अधिसूचनाओं से पुष्टि करें।",
  "No liability.": "कोई दायित्व नहीं।",
  "This website is provided \"as is\", without any warranty of accuracy or completeness. NE Media is not responsible for any loss, claim or decision arising from its use. By using this calculator you accept these terms.": "यह वेबसाइट \"जैसी है\" के आधार पर दी जाती है, सटीकता या पूर्णता की किसी गारंटी के बिना। इसके उपयोग से होने वाली किसी हानि, दावे या निर्णय के लिए NE Media ज़िम्मेदार नहीं है। इस कैलकुलेटर का उपयोग करके आप इन शर्तों को स्वीकार करते हैं।",
  "Your data stays with you.": "आपका डेटा आपके पास रहता है।",
  "All calculations run in your browser. The figures you enter are not saved or sent anywhere by this calculator.": "सभी गणनाएँ आपके ब्राउज़र में होती हैं। आपके डाले गए आंकड़े यह कैलकुलेटर न सहेजता है, न कहीं भेजता है।",
  "Advertisements.": "विज्ञापन।",
  "Ads are shown by third parties. Their appearance here is not an endorsement of any product, service or offer.": "विज्ञापन तीसरे पक्ष दिखाते हैं। यहाँ उनका दिखना किसी उत्पाद, सेवा या ऑफ़र का समर्थन नहीं है।",
  "Rates last reviewed: September 2026.": "दरों की अंतिम समीक्षा: सितंबर 2026।",
  "Questions or corrections:": "प्रश्न या सुधार:",
  "© 2026 NE Media · Pay Commission Calculator · Estimates only, not an official Government tool.": "© 2026 NE Media · वेतन आयोग कैलकुलेटर · केवल अनुमान, आधिकारिक सरकारी टूल नहीं।",
  // Accessibility labels
  "Choose pay commission": "वेतन आयोग चुनें", "8th Pay Commission calculator": "8वें वेतन आयोग का कैलकुलेटर", "Main": "मुख्य", "Footer": "फ़ुटर",
  "Advertisement": "विज्ञापन"
};

window.I18N_RULES = [
  [/^Level (\w+) · (.+) · from (₹[\d,]+)$/, m => `लेवल ${m[1]} · ${m[2].replace("Cabinet Secretary", "कैबिनेट सचिव").replace("Apex", "एपेक्स")} · ${m[3]} से`],
  [/^Academic Level (\w+) · (.+) · from (₹[\d,]+)$/, m => `एकेडमिक लेवल ${m[1]} · ${m[2]} · ${m[3]} से`],
  [/^(Academic )?Level (\w+)( \([^)]+\))?: (₹[\d,]+) to (₹[\d,]+)\.$/, m => `${m[1] ? "एकेडमिक " : ""}लेवल ${m[2]}${m[3] || ""}: ${m[4]} से ${m[5]} तक।`],
  [/^(Academic )?Level (\w+)( \([^)]+\))? has one basic pay: (₹[\d,]+)\.$/, m => `${m[1] ? "एकेडमिक " : ""}लेवल ${m[2]}${m[3] || ""} में केवल एक मूल वेतन है: ${m[4]}।`],
  [/^(₹[\d,]+) is outside this level\. (.+)$/, (m, t) => `${m[1]} इस लेवल की सीमा से बाहर है। ${t(m[2])}`],
  [/^"(.+)" is not on the X or Y list, so it is Class Z\. Change the class below if your office says otherwise\.$/, m => `"${m[1]}" X या Y सूची में नहीं है, इसलिए यह श्रेणी Z है। यदि आपका कार्यालय कुछ और कहे तो नीचे श्रेणी बदलें।`],
  [/^(.+): Class ([XYZ])\. HRA class set to [XYZ]\.$/, m => `${m[1]}: श्रेणी ${m[2]}। HRA श्रेणी ${m[2]} कर दी गई।`],
  [/^HRA class chosen manually: Class ([XYZ])\.$/, m => `HRA श्रेणी स्वयं चुनी गई: श्रेणी ${m[1]}।`],
  [/^(?:(.+) · )?Class ([XYZ]) · (\d+)%$/, m => `${m[1] ? m[1] + " · " : ""}श्रेणी ${m[2]} · ${m[3]}%`],
  [/^(\d+) added · \+(₹[\d,]+)$/, m => `${m[1]} जोड़े गए · +${m[2]}`],
  [/^(New|Old) regime · (₹[\d,]+)\/mo$/, m => `${rg(m[1])} · ${m[2]}/माह`],
  [/^(₹[\d,]+)\/mo$/, m => `${m[1]}/माह`],
  [/^(new|old) regime · per month$/, m => `${rg(m[1])} · प्रति माह`],
  [/^(New|Old) regime saves (₹[\d,]+)$/, m => `${rg(m[1])} में ${m[2]} की बचत`],
  [/^(NPS|UPS) \(([\d.]+)% of basic \+ DA\)$/, m => `${m[1]} (मूल वेतन + DA का ${m[2]}%)`],
  [/^(NPS|UPS) on arrears \(([\d.]+)%\)$/, m => `एरियर पर ${m[1]} (${m[2]}%)`],
  [/^Yearly tax · (.+)$/, (m, t) => `वार्षिक कर · ${t(m[1])}`],
  [/^Slab-wise tax · (new|old) regime$/, m => `स्लैब-वार कर · ${rg(m[1])}`],
  [/^(₹[\d,]+) – above$/, m => `${m[1]} से अधिक`],
  [/^(\d+) months · (\w{3} \d{4}) to (\w{3} \d{4})$/, m => `${m[1]} महीने · ${mon(m[2])} से ${mon(m[3])} तक`],
  [/^(\d+) periods? · (\d+) months$/, m => `${m[1]} अवधि · ${m[2]} महीने`],
  [/^(\d+) months? · DA (\d+)% → (\d+)%$/, m => `${m[1]} महीने · DA ${m[2]}% → ${m[3]}%`],
  [/^basic (₹[\d,]+)$/, m => `मूल ${m[1]}`],
  [/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}( – (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4})?$/, m => mon(m[0])],
  [/^(January|February|March|April|May|June|July|August|September|October|November|December) (\d{4})$/, m => `${MONTH[m[1]]} ${m[2]}`],
  [/^FY (\d{4}-\d{2}), (new|old) regime(?:, after (₹[\d,]+) Section 89 relief)?$/, m => `वित्त वर्ष ${m[1]}, ${rg(m[2])}${m[3] ? `, ${m[3]} धारा 89 राहत के बाद` : ""}`],
  [/^FY (\d{4}-\d{2})$/, m => `वित्त वर्ष ${m[1]}`],
  [/^Tax in the year you receive arrears · FY (\S+), (new|old) regime$/, m => `एरियर मिलने वाले वर्ष में कर · वित्त वर्ष ${m[1]}, ${rg(m[2])}`],
  [/^Extra tax on these arrears if taxed in FY (\S+)$/, m => `इन एरियर पर अतिरिक्त कर, यदि वित्त वर्ष ${m[1]} में कर लगे`],
  [/^Section 89 saves (₹[\d,]+)$/, m => `धारा 89 से ${m[1]} की बचत`],
  [/^All arrears belong to FY (\S+), so there is no Section 89 relief\.$/, m => `सारे एरियर वित्त वर्ष ${m[1]} के हैं, इसलिए धारा 89 राहत नहीं मिलेगी।`],
  [/^Estimated arrears receivable after (tax and )?(NPS|UPS)$/, m => `${m[1] ? "कर और " : ""}${m[2]} के बाद अनुमानित प्राप्य एरियर`],
  [/^Arrears are the difference between 8th CPC pay due and 7th CPC pay actually paid, on (.+)\.$/, m =>
    `एरियर, 8वें वेतन आयोग के देय वेतन और 7वें वेतन आयोग के वास्तव में मिले वेतन का अंतर है: ${m[1].replace("basic pay and DA", "मूल वेतन और DA").replace("transport allowance", "परिवहन भत्ता").replace(/ and /g, " और ")} पर।`],
  [/^7th CPC DA is taken as (\d+)% from January 2026 and 8th CPC DA as 0% from (\w{3} \d{4}), both rising ([\d.]+)% every January and July\.$/, m =>
    `7वें वेतन आयोग का DA जनवरी 2026 से ${m[1]}% और 8वें वेतन आयोग का DA ${mon(m[2])} से 0% माना गया है; दोनों हर जनवरी और जुलाई में ${m[3]}% बढ़ते हैं।`]
];
})();
